version: '3.8'
services:
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: smarteduhub_db
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=smarteduhub
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #     - ./resource/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
  #     - ./resource/data.sql:/docker-entrypoint-initdb.d/02_data.sql
  #   networks:
  #     - smarteduhub_net

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: smarteduhub_minio
    ports:
      - "9000:9000" # API 端口
      - "9001:9001" # 控制台端口
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: server /data --console-address ":9001"
    volumes:
      - /Users/yutong/docker-data/minio:/data # 挂载本地目录到容器
    networks:
      - smarteduhub_net

networks:
  smarteduhub_net:
    driver: bridge

# volumes:
  # postgres_data:
  # minio_data: